-- =====================================================================
--  Workflow Control Plane — PostgreSQL schema (v3: workspaces + token pool)
--
--  Target    : PostgreSQL 18 (Azure Database for PostgreSQL Flexible Server)
--  Owned by  : the app's `server/db` (Drizzle schema mirrors this file;
--              triggers/functions live in hand-written SQL migrations)
--  Verify    : psql -v ON_ERROR_STOP=1 -f schema.sql -f schema-checks.sql
--
--  What changed from the previous version
--    * A WORKSPACE is an imported GitHub repository. Only app admins import.
--    * Access = workspace visibility (private / public) + grants to users or
--      Entra ID groups. No GitHub-derived permissions.
--    * Identity = Microsoft Entra ID via Better Auth (schema "auth").
--      The user's GitHub username is stored for attribution only.
--    * GitHub is called through a POOL of credentials (PATs and/or GitHub App
--      installations). Rate limits are tracked per BUCKET (per GitHub account
--      or installation), because GitHub limits per account, not per token.
--    * Two process roles: web (Next.js) and worker. Ingest lives in web.
--    * Policies folded into per-workflow settings (approval, refs, concurrency).
--
--  Unchanged: intent vs mirror, state machine guard, forward-only GitHub status,
--  frozen WANTED, outbox events (append-only, commit-safe feed), Postgres work
--  queue + leases, webhook inbox dedupe.
-- =====================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS cp;

-- =====================================================================
-- 1. Vocabularies
-- =====================================================================

-- GitHub status (+ conclusion) -> rank. Never moves to a lower rank.
CREATE OR REPLACE FUNCTION cp.github_status_rank(p_status text, p_conclusion text)
RETURNS smallint LANGUAGE sql IMMUTABLE AS $$
    SELECT (CASE
        WHEN p_status = 'requested'                                     THEN 1
        WHEN p_status IN ('queued', 'pending')                          THEN 2
        WHEN p_status IN ('waiting', 'in_progress')                     THEN 3
        WHEN p_status = 'completed' AND p_conclusion = 'action_required' THEN 3
        WHEN p_status = 'completed'                                     THEN 5
        ELSE 0
    END)::smallint
$$;

-- Run-request state machine, as data.
CREATE OR REPLACE FUNCTION cp.phase_transition_allowed(p_from text, p_to text)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
    SELECT p_from = p_to OR (p_from, p_to) IN (
        ('pending','awaiting_approval'), ('pending','waiting_for_slot'), ('pending','dispatching'),
        ('pending','rejected'), ('pending','cancelled'),
        ('awaiting_approval','waiting_for_slot'), ('awaiting_approval','dispatching'),
        ('awaiting_approval','rejected'), ('awaiting_approval','cancelled'),
        ('waiting_for_slot','dispatching'), ('waiting_for_slot','rejected'), ('waiting_for_slot','cancelled'),
        ('dispatching','verifying'), ('dispatching','dispatched'), ('dispatching','running'),
        ('dispatching','succeeded'), ('dispatching','failed'), ('dispatching','cancelled'),
        ('dispatching','cancelling'), ('dispatching','lost'),
        ('verifying','dispatching'), ('verifying','dispatched'), ('verifying','running'),
        ('verifying','succeeded'), ('verifying','failed'), ('verifying','cancelled'),
        ('verifying','cancelling'), ('verifying','lost'),
        ('dispatched','running'), ('dispatched','succeeded'), ('dispatched','failed'),
        ('dispatched','cancelled'), ('dispatched','cancelling'),
        ('running','succeeded'), ('running','failed'), ('running','cancelled'), ('running','cancelling'),
        ('cancelling','cancelled'), ('cancelling','succeeded'), ('cancelling','failed')
    )
$$;

-- =====================================================================
-- 2. Identity — Better Auth tables (schema "auth")
--    Configure Better Auth with modelName users/sessions/accounts/verifications,
--    UUID ids generated by the database, and the additional user fields below.
--    The Better Auth CLI output must match this shape (checked in CI).
-- =====================================================================

CREATE TABLE auth.users (
    id                      uuid        PRIMARY KEY DEFAULT uuidv7(),
    name                    text        NOT NULL,
    email                   text        NOT NULL UNIQUE,
    email_verified          boolean     NOT NULL DEFAULT false,
    image                   text,
    -- additional fields (ours)
    role                    text        NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    is_active               boolean     NOT NULL DEFAULT true,
    entra_object_id         text        UNIQUE,                 -- Entra "oid" (stable)
    github_user_id          bigint      UNIQUE,                 -- stable key on GitHub
    github_login            text,                               -- refreshed; can change on rename
    github_avatar_url       text,
    github_identity_source  text        CHECK (github_identity_source IN ('saml', 'self_declared', 'admin')),
    github_synced_at        timestamptz,
    last_login_at           timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CHECK ((github_user_id IS NULL) = (github_login IS NULL))
);

CREATE TABLE auth.sessions (
    id          uuid        PRIMARY KEY DEFAULT uuidv7(),
    token       text        NOT NULL UNIQUE,
    user_id     uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    expires_at  timestamptz NOT NULL,
    ip_address  text,
    user_agent  text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_idx ON auth.sessions (user_id);

CREATE TABLE auth.accounts (
    id                        uuid        PRIMARY KEY DEFAULT uuidv7(),
    account_id                text        NOT NULL,            -- Entra oid for provider 'microsoft'
    provider_id               text        NOT NULL,            -- 'microsoft'
    user_id                   uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    access_token              text,
    refresh_token             text,
    id_token                  text,
    access_token_expires_at   timestamptz,
    refresh_token_expires_at  timestamptz,
    scope                     text,
    password                  text,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_id, account_id)
);
CREATE INDEX accounts_user_idx ON auth.accounts (user_id);

CREATE TABLE auth.verifications (
    id          uuid        PRIMARY KEY DEFAULT uuidv7(),
    identifier  text        NOT NULL,
    value       text        NOT NULL,
    expires_at  timestamptz NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Entra ID groups seen in users' tokens (synced at every login).
CREATE TABLE cp.directory_groups (
    id            text        PRIMARY KEY,                     -- Entra group object id
    display_name  text,
    last_seen_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE cp.user_groups (
    user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    group_id   text        NOT NULL REFERENCES cp.directory_groups(id) ON DELETE CASCADE,
    synced_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, group_id)
);
CREATE INDEX user_groups_group_idx ON cp.user_groups (group_id);

-- =====================================================================
-- 3. GitHub credential pool
--    Secrets are NEVER stored here: secret_ref names a Key Vault secret.
--    rate_bucket groups credentials that share one GitHub rate limit:
--      'user:<github account id>'      for personal access tokens
--      'installation:<installation id>' for GitHub App installations
-- =====================================================================

CREATE TABLE cp.github_credentials (
    id                    uuid        PRIMARY KEY DEFAULT uuidv7(),
    label                 text        NOT NULL UNIQUE,         -- 'release-bot PAT #2'
    kind                  text        NOT NULL CHECK (kind IN ('fine_grained_pat', 'classic_pat', 'github_app')),
    secret_ref            text        NOT NULL,                -- Key Vault secret name
    github_account_id     bigint,                              -- owner of a PAT
    github_account_login  text,
    app_id                bigint,                              -- for github_app
    installation_id       bigint,                              -- for github_app
    rate_bucket           text        NOT NULL,
    status                text        NOT NULL DEFAULT 'active'
                                      CHECK (status IN ('active', 'disabled', 'expired', 'invalid')),
    priority              smallint    NOT NULL DEFAULT 100,    -- lower = preferred
    expires_at            timestamptz,                         -- PAT expiry (from GitHub response header)
    last_used_at          timestamptz,
    last_error            text,
    consecutive_failures  int         NOT NULL DEFAULT 0,
    created_by            uuid        NOT NULL REFERENCES auth.users(id),
    resource_version      bigint      NOT NULL DEFAULT 1,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CHECK ((kind = 'github_app') = (installation_id IS NOT NULL AND app_id IS NOT NULL)),
    CHECK ((kind = 'github_app') OR github_account_id IS NOT NULL),
    CHECK (rate_bucket = CASE WHEN kind = 'github_app'
                              THEN 'installation:' || installation_id
                              ELSE 'user:' || github_account_id END)
);
CREATE INDEX github_credentials_active_idx ON cp.github_credentials (rate_bucket) WHERE status = 'active';

-- Live rate-limit state per bucket and GitHub "resource" (core, graphql, search, ...).
CREATE TABLE cp.github_rate_buckets (
    rate_bucket           text        NOT NULL,
    resource              text        NOT NULL DEFAULT 'core',
    limit_total           int,
    remaining             int,
    resets_at             timestamptz,
    blocked_until         timestamptz,                         -- secondary limit / Retry-After
    breaker_state         text        NOT NULL DEFAULT 'closed' CHECK (breaker_state IN ('closed', 'open', 'half_open')),
    consecutive_failures  int         NOT NULL DEFAULT 0,
    updated_at            timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (rate_bucket, resource)
);

-- =====================================================================
-- 4. Workspaces — one imported GitHub repository each
-- =====================================================================

CREATE TABLE cp.workspaces (
    id                 uuid        PRIMARY KEY DEFAULT uuidv7(),
    github_repo_id     bigint      NOT NULL UNIQUE,            -- stable across renames
    owner_login        text        NOT NULL,
    repo_name          text        NOT NULL,
    full_name          text        NOT NULL UNIQUE,            -- owner/name (refreshed on sync)
    default_branch     text        NOT NULL,
    display_name       text        NOT NULL,
    description        text,
    visibility         text        NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'public')),
    public_role        text        CHECK (public_role IN ('viewer', 'operator')),
    status             text        NOT NULL DEFAULT 'importing'
                                   CHECK (status IN ('importing', 'active', 'error', 'archived')),
    status_reason      text,
    update_mode        text        NOT NULL DEFAULT 'polling' CHECK (update_mode IN ('webhook', 'polling')),
    github_hook_id     bigint,                                 -- when we registered the repo webhook
    imported_by        uuid        NOT NULL REFERENCES auth.users(id),
    imported_at        timestamptz NOT NULL DEFAULT now(),
    last_synced_at     timestamptz,
    runs_listed_until  timestamptz,                            -- Checker "warm" checkpoint
    resource_version   bigint      NOT NULL DEFAULT 1,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    CHECK ((visibility = 'public') = (public_role IS NOT NULL)),
    CHECK ((update_mode = 'webhook') = (github_hook_id IS NOT NULL))
);

-- Who may use a private workspace (and extra rights in a public one).
CREATE TABLE cp.workspace_grants (
    id             uuid        PRIMARY KEY DEFAULT uuidv7(),
    workspace_id   uuid        NOT NULL REFERENCES cp.workspaces(id) ON DELETE CASCADE,
    subject_type   text        NOT NULL CHECK (subject_type IN ('user', 'group')),
    subject_id     text        NOT NULL,                       -- users.id (uuid text) or Entra group id
    role           text        NOT NULL CHECK (role IN ('viewer', 'operator')),
    can_approve    boolean     NOT NULL DEFAULT false,
    environments   text[],                                     -- NULL = any (applies to operator)
    granted_by     uuid        NOT NULL REFERENCES auth.users(id),
    granted_at     timestamptz NOT NULL DEFAULT now(),
    expires_at     timestamptz,
    UNIQUE (workspace_id, subject_type, subject_id)
);
CREATE INDEX workspace_grants_subject_idx ON cp.workspace_grants (subject_type, subject_id);

-- Which pool credentials may serve a workspace (validated at import / re-validated on failure).
CREATE TABLE cp.workspace_credentials (
    workspace_id   uuid        NOT NULL REFERENCES cp.workspaces(id) ON DELETE CASCADE,
    credential_id  uuid        NOT NULL REFERENCES cp.github_credentials(id) ON DELETE CASCADE,
    can_dispatch   boolean     NOT NULL,                       -- Actions write verified
    validated_at   timestamptz NOT NULL DEFAULT now(),
    last_error     text,
    PRIMARY KEY (workspace_id, credential_id)
);
CREATE INDEX workspace_credentials_cred_idx ON cp.workspace_credentials (credential_id);

-- Workflows: discovered columns (worker) + curation and run settings (admins).
CREATE TABLE cp.workflows (
    id                     bigint      PRIMARY KEY,            -- GitHub workflow id
    workspace_id           uuid        NOT NULL REFERENCES cp.workspaces(id) ON DELETE CASCADE,
    -- discovered
    path                   text        NOT NULL,
    name                   text        NOT NULL,
    gh_state               text        NOT NULL,
    -- curation
    exposed                boolean     NOT NULL DEFAULT false,
    display_name           text,
    description            text,
    category               text,
    icon                   text,
    ui_schema              jsonb       NOT NULL DEFAULT '{}',
    -- run settings (formerly "policies")
    allowed_ref_patterns   text[],                             -- NULL = any ref
    approval_required      boolean     NOT NULL DEFAULT false,
    approval_environments  text[],                             -- NULL = all environments
    approval_min           smallint    NOT NULL DEFAULT 1 CHECK (approval_min BETWEEN 1 AND 5),
    approval_ttl           interval    NOT NULL DEFAULT interval '24 hours',
    concurrency_scope      text        NOT NULL DEFAULT 'none'
                                       CHECK (concurrency_scope IN ('none', 'workflow', 'workflow_environment')),
    concurrency_policy     text        NOT NULL DEFAULT 'allow' CHECK (concurrency_policy IN ('allow', 'forbid', 'queue')),
    resource_version       bigint      NOT NULL DEFAULT 1,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, path),
    CHECK ((concurrency_scope = 'none') = (concurrency_policy = 'allow'))
);
CREATE INDEX workflows_exposed_idx ON cp.workflows (workspace_id) WHERE exposed;

CREATE TABLE cp.workflow_definitions (
    workflow_id       bigint      NOT NULL REFERENCES cp.workflows(id) ON DELETE CASCADE,
    ref               text        NOT NULL,
    commit_sha        text        NOT NULL,
    has_dispatch      boolean     NOT NULL,
    input_schema      jsonb       NOT NULL DEFAULT '{"type":"object","properties":{}}',
    run_name_has_tag  boolean     NOT NULL,
    parse_problems    text[]      NOT NULL DEFAULT '{}',
    fetched_at        timestamptz NOT NULL DEFAULT now(),
    resource_version  bigint      NOT NULL DEFAULT 1,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workflow_id, ref)
);

-- =====================================================================
-- 5. Runs — intent (WANTED) and progress
-- =====================================================================

CREATE TABLE cp.run_requests (
    id                   uuid        PRIMARY KEY DEFAULT uuidv7(),
    correlation_tag      text        NOT NULL UNIQUE
                                     DEFAULT 'cp-' || substr(md5(gen_random_uuid()::text), 1, 12),
    idempotency_key      text        NOT NULL,
    -- WANTED (frozen)
    requested_by         uuid        NOT NULL REFERENCES auth.users(id),
    workspace_id         uuid        NOT NULL REFERENCES cp.workspaces(id),
    workflow_id          bigint      NOT NULL REFERENCES cp.workflows(id),
    ref                  text        NOT NULL,
    inputs               jsonb       NOT NULL DEFAULT '{}',
    environment          text,
    concurrency_key      text,
    concurrency_policy   text        NOT NULL DEFAULT 'allow' CHECK (concurrency_policy IN ('allow', 'forbid', 'queue')),
    settings_snapshot    jsonb       NOT NULL DEFAULT '{}',    -- approval/ref rules applied, for audit
    cancel_requested     boolean     NOT NULL DEFAULT false,
    cancel_requested_by  uuid        REFERENCES auth.users(id),
    cancel_requested_at  timestamptz,
    -- PROGRESS (worker)
    phase                text        NOT NULL DEFAULT 'pending' CHECK (phase IN (
                                       'pending', 'awaiting_approval', 'waiting_for_slot',
                                       'dispatching', 'verifying', 'dispatched', 'running', 'cancelling',
                                       'succeeded', 'failed', 'cancelled', 'rejected', 'lost')),
    phase_reason         text,
    phase_message        text,
    conditions           jsonb       NOT NULL DEFAULT '[]',
    github_run_id        bigint,
    dispatched_with      uuid        REFERENCES cp.github_credentials(id),  -- which credential sent it
    dispatch_attempts    smallint    NOT NULL DEFAULT 0,
    dispatch_sent_at     timestamptz,
    verify_until         timestamptz,
    resource_version     bigint      NOT NULL DEFAULT 1,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (requested_by, idempotency_key),
    CHECK (concurrency_policy = 'allow' OR concurrency_key IS NOT NULL)
);
CREATE UNIQUE INDEX run_requests_github_run_uidx ON cp.run_requests (github_run_id) WHERE github_run_id IS NOT NULL;
CREATE INDEX run_requests_open_idx ON cp.run_requests (phase, updated_at)
    WHERE phase IN ('pending','awaiting_approval','waiting_for_slot','dispatching','verifying','dispatched','running','cancelling');
CREATE INDEX run_requests_by_requester_idx ON cp.run_requests (requested_by, created_at DESC);
CREATE INDEX run_requests_by_workspace_idx ON cp.run_requests (workspace_id, created_at DESC);
CREATE UNIQUE INDEX run_requests_one_active_per_slot ON cp.run_requests (concurrency_key)
    WHERE concurrency_policy IN ('forbid', 'queue')
      AND phase IN ('dispatching', 'verifying', 'dispatched', 'running', 'cancelling');

CREATE TABLE cp.run_actions (
    id                uuid        PRIMARY KEY DEFAULT uuidv7(),
    idempotency_key   text        NOT NULL,
    requested_by      uuid        NOT NULL REFERENCES auth.users(id),
    workspace_id      uuid        NOT NULL REFERENCES cp.workspaces(id),
    github_run_id     bigint      NOT NULL,
    run_attempt       int         NOT NULL,
    action            text        NOT NULL CHECK (action IN ('cancel', 'rerun_all', 'rerun_failed', 'rerun_job')),
    job_id            bigint,
    phase             text        NOT NULL DEFAULT 'pending' CHECK (phase IN ('pending', 'sending', 'done', 'failed', 'rejected')),
    phase_reason      text,
    result_attempt    int,
    resource_version  bigint      NOT NULL DEFAULT 1,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (requested_by, idempotency_key),
    CHECK ((action = 'rerun_job') = (job_id IS NOT NULL))
);
CREATE INDEX run_actions_open_idx ON cp.run_actions (phase, updated_at) WHERE phase IN ('pending', 'sending');

CREATE TABLE cp.approval_requests (
    run_request_id    uuid        PRIMARY KEY REFERENCES cp.run_requests(id),
    workspace_id      uuid        NOT NULL REFERENCES cp.workspaces(id),
    min_approvals     smallint    NOT NULL,
    state             text        NOT NULL DEFAULT 'pending'
                                  CHECK (state IN ('pending', 'approved', 'denied', 'expired', 'withdrawn')),
    expires_at        timestamptz NOT NULL,
    decided_at        timestamptz,
    resource_version  bigint      NOT NULL DEFAULT 1,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX approval_requests_pending_idx ON cp.approval_requests (workspace_id, expires_at) WHERE state = 'pending';

CREATE TABLE cp.approval_decisions (
    run_request_id  uuid        NOT NULL REFERENCES cp.approval_requests(run_request_id),
    approver_id     uuid        NOT NULL REFERENCES auth.users(id),
    decision        text        NOT NULL CHECK (decision IN ('approve', 'deny')),
    comment         text,
    decided_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_request_id, approver_id)
);

-- =====================================================================
-- 6. Mirror — what GitHub says happened
-- =====================================================================

CREATE TABLE cp.workflow_runs (
    run_id                  bigint      NOT NULL,
    run_attempt             int         NOT NULL,
    workspace_id            uuid        NOT NULL,
    workflow_id             bigint      NOT NULL,
    run_request_id          uuid        REFERENCES cp.run_requests(id),
    event                   text,
    display_title           text,
    head_branch             text,
    head_sha                text,
    actor_login             text,
    triggering_actor_login  text,
    html_url                text,
    status                  text        NOT NULL CHECK (status IN
                                          ('requested','queued','pending','waiting','in_progress','completed')),
    conclusion              text,
    status_rank             smallint    GENERATED ALWAYS AS (cp.github_status_rank(status, conclusion)) STORED,
    gh_created_at           timestamptz NOT NULL,
    gh_updated_at           timestamptz NOT NULL,
    run_started_at          timestamptz,
    completed_at            timestamptz,
    last_seen_at            timestamptz NOT NULL DEFAULT now(),
    last_seen_via           text        NOT NULL CHECK (last_seen_via IN ('webhook', 'poll')),
    etag                    text,
    resource_version        bigint      NOT NULL DEFAULT 1,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, run_attempt)
);
CREATE INDEX workflow_runs_by_workspace_idx ON cp.workflow_runs (workspace_id, gh_created_at DESC);
CREATE INDEX workflow_runs_by_workflow_idx  ON cp.workflow_runs (workflow_id, gh_created_at DESC);
CREATE INDEX workflow_runs_by_request_idx   ON cp.workflow_runs (run_request_id) WHERE run_request_id IS NOT NULL;
CREATE INDEX workflow_runs_unfinished_idx   ON cp.workflow_runs (last_seen_at) WHERE status <> 'completed';

CREATE TABLE cp.workflow_jobs (
    id                bigint      PRIMARY KEY,
    run_id            bigint      NOT NULL,
    run_attempt       int         NOT NULL,
    workspace_id      uuid        NOT NULL,
    name              text        NOT NULL,
    status            text        NOT NULL CHECK (status IN
                                    ('requested','queued','pending','waiting','in_progress','completed')),
    conclusion        text,
    status_rank       smallint    GENERATED ALWAYS AS (cp.github_status_rank(status, conclusion)) STORED,
    runner_name       text,
    labels            text[]      NOT NULL DEFAULT '{}',
    steps             jsonb       NOT NULL DEFAULT '[]',
    html_url          text,
    started_at        timestamptz,
    completed_at      timestamptz,
    last_seen_at      timestamptz NOT NULL DEFAULT now(),
    last_seen_via     text        NOT NULL CHECK (last_seen_via IN ('webhook', 'poll')),
    resource_version  bigint      NOT NULL DEFAULT 1,
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX workflow_jobs_by_run_idx ON cp.workflow_jobs (run_id, run_attempt);

-- =====================================================================
-- 7. Events — outbox = live stream = audit trail
-- =====================================================================

CREATE SEQUENCE cp.events_seq;

CREATE TABLE cp.events (
    seq                bigint      NOT NULL DEFAULT nextval('cp.events_seq'),
    txid               xid8        NOT NULL DEFAULT pg_current_xact_id(),
    id                 uuid        NOT NULL DEFAULT uuidv7(),
    type               text        NOT NULL,
    version            smallint    NOT NULL,
    occurred_at        timestamptz NOT NULL DEFAULT now(),
    subject            text        NOT NULL,
    aggregate_type     text        NOT NULL,
    aggregate_id       text        NOT NULL,
    aggregate_version  bigint,
    actor_kind         text        NOT NULL CHECK (actor_kind IN ('user', 'system', 'github')),
    actor_id           text,
    workspace_id       uuid,                                   -- scope for filtering + authorization
    workflow_id        bigint,
    correlation_id     text,
    causation_id       uuid,
    data               jsonb       NOT NULL,
    PRIMARY KEY (occurred_at, seq)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX events_feed_idx      ON cp.events (txid, seq);
CREATE INDEX events_aggregate_idx ON cp.events (aggregate_type, aggregate_id, seq);
CREATE INDEX events_workspace_idx ON cp.events (workspace_id, occurred_at);

CREATE TABLE cp.event_consumers (
    name        text        PRIMARY KEY,
    last_txid   xid8        NOT NULL DEFAULT '0'::xid8,
    last_seq    bigint      NOT NULL DEFAULT 0,
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- 8. Plumbing
-- =====================================================================

CREATE TABLE cp.work_queue (
    queue         text        NOT NULL,
    key           text        NOT NULL,
    priority      smallint    NOT NULL DEFAULT 100,
    run_after     timestamptz NOT NULL DEFAULT now(),
    attempts      int         NOT NULL DEFAULT 0,
    locked_by     text,
    locked_until  timestamptz,
    dirty         boolean     NOT NULL DEFAULT false,
    last_error    text,
    enqueued_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (queue, key)
) WITH (fillfactor = 70);
CREATE INDEX work_queue_ready_idx ON cp.work_queue (queue, priority, run_after);

CREATE TABLE cp.leases (
    name           text        PRIMARY KEY,
    holder         text        NOT NULL,
    fencing_token  bigint      NOT NULL,
    expires_at     timestamptz NOT NULL
);

CREATE TABLE cp.inbox_seen (
    delivery_guid  uuid        PRIMARY KEY,
    seen_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX inbox_seen_age_idx ON cp.inbox_seen (seen_at);

CREATE TABLE cp.webhook_deliveries (
    delivery_guid   uuid        NOT NULL,
    received_at     timestamptz NOT NULL DEFAULT now(),
    event_type      text        NOT NULL,
    action          text,
    github_repo_id  bigint,
    payload         jsonb       NOT NULL,
    process_status  text        NOT NULL DEFAULT 'pending'
                                CHECK (process_status IN ('pending', 'applied', 'ignored', 'failed', 'dead')),
    attempts        int         NOT NULL DEFAULT 0,
    processed_at    timestamptz,
    last_error      text,
    PRIMARY KEY (received_at, delivery_guid)
) PARTITION BY RANGE (received_at);
CREATE INDEX webhook_deliveries_todo_idx ON cp.webhook_deliveries (received_at) WHERE process_status IN ('pending', 'failed');

CREATE TABLE cp.github_http_cache (
    cache_key   text        PRIMARY KEY,
    etag        text        NOT NULL,
    body        jsonb       NOT NULL,
    fetched_at  timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- 9. Guards
-- =====================================================================

CREATE OR REPLACE FUNCTION cp.bump_version()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    housekeeping constant text[] := ARRAY[
        'resource_version', 'updated_at', 'last_seen_at', 'last_seen_via', 'etag', 'status_rank',
        'runs_listed_until', 'last_synced_at', 'fetched_at', 'last_used_at'];
BEGIN
    IF (to_jsonb(NEW) - housekeeping) = (to_jsonb(OLD) - housekeeping) THEN
        RETURN NEW;
    END IF;
    NEW.resource_version := OLD.resource_version + 1;
    NEW.updated_at       := now();
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION cp.protect_wanted()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.requested_by, NEW.workspace_id, NEW.workflow_id, NEW.ref, NEW.inputs, NEW.environment,
        NEW.concurrency_key, NEW.concurrency_policy, NEW.settings_snapshot,
        NEW.correlation_tag, NEW.idempotency_key, NEW.created_at)
       IS DISTINCT FROM
       (OLD.requested_by, OLD.workspace_id, OLD.workflow_id, OLD.ref, OLD.inputs, OLD.environment,
        OLD.concurrency_key, OLD.concurrency_policy, OLD.settings_snapshot,
        OLD.correlation_tag, OLD.idempotency_key, OLD.created_at) THEN
        RAISE EXCEPTION 'run_request %: WANTED fields are frozen after creation', OLD.id;
    END IF;
    IF OLD.cancel_requested AND NOT NEW.cancel_requested THEN
        RAISE EXCEPTION 'run_request %: a cancel request cannot be withdrawn', OLD.id;
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION cp.guard_phase_transition()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT cp.phase_transition_allowed(OLD.phase, NEW.phase) THEN
        RAISE EXCEPTION 'run_request %: illegal phase transition % -> %', OLD.id, OLD.phase, NEW.phase;
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION cp.guard_forward_only()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF cp.github_status_rank(NEW.status, NEW.conclusion) < cp.github_status_rank(OLD.status, OLD.conclusion) THEN
        RAISE EXCEPTION '%: status may not move backwards (% -> %)', TG_TABLE_NAME, OLD.status, NEW.status;
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION cp.forbid_self_approval()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM cp.run_requests WHERE id = NEW.run_request_id AND requested_by = NEW.approver_id) THEN
        RAISE EXCEPTION 'user % cannot approve their own run request %', NEW.approver_id, NEW.run_request_id;
    END IF;
    RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION cp.forbid_change()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only (% not allowed)', TG_TABLE_NAME, TG_OP;
END
$$;

CREATE TRIGGER a_protect_wanted     BEFORE UPDATE ON cp.run_requests       FOR EACH ROW EXECUTE FUNCTION cp.protect_wanted();
CREATE TRIGGER b_guard_phase        BEFORE UPDATE OF phase ON cp.run_requests FOR EACH ROW EXECUTE FUNCTION cp.guard_phase_transition();
CREATE TRIGGER b_guard_forward_only BEFORE UPDATE ON cp.workflow_runs      FOR EACH ROW EXECUTE FUNCTION cp.guard_forward_only();
CREATE TRIGGER b_guard_forward_only BEFORE UPDATE ON cp.workflow_jobs      FOR EACH ROW EXECUTE FUNCTION cp.guard_forward_only();
CREATE TRIGGER a_no_self_approval   BEFORE INSERT ON cp.approval_decisions FOR EACH ROW EXECUTE FUNCTION cp.forbid_self_approval();
CREATE TRIGGER a_append_only        BEFORE UPDATE OR DELETE ON cp.approval_decisions FOR EACH ROW EXECUTE FUNCTION cp.forbid_change();
CREATE TRIGGER a_append_only        BEFORE UPDATE OR DELETE ON cp.events   FOR EACH ROW EXECUTE FUNCTION cp.forbid_change();

CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.github_credentials   FOR EACH ROW EXECUTE FUNCTION cp.bump_version();
CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.workspaces           FOR EACH ROW EXECUTE FUNCTION cp.bump_version();
CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.workflows            FOR EACH ROW EXECUTE FUNCTION cp.bump_version();
CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.workflow_definitions FOR EACH ROW EXECUTE FUNCTION cp.bump_version();
CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.run_requests         FOR EACH ROW EXECUTE FUNCTION cp.bump_version();
CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.run_actions          FOR EACH ROW EXECUTE FUNCTION cp.bump_version();
CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.approval_requests    FOR EACH ROW EXECUTE FUNCTION cp.bump_version();
CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.workflow_runs        FOR EACH ROW EXECUTE FUNCTION cp.bump_version();
CREATE TRIGGER z_bump_version BEFORE UPDATE ON cp.workflow_jobs        FOR EACH ROW EXECUTE FUNCTION cp.bump_version();

-- =====================================================================
-- 10. Functions
-- =====================================================================

CREATE OR REPLACE FUNCTION cp.enqueue(p_queue text, p_key text,
                                      p_delay interval DEFAULT interval '0', p_priority int DEFAULT 100)
RETURNS void LANGUAGE sql AS $$
    INSERT INTO cp.work_queue AS q (queue, key, run_after, priority)
    VALUES (p_queue, p_key, now() + p_delay, p_priority)
    ON CONFLICT (queue, key) DO UPDATE
       SET run_after = LEAST(q.run_after, EXCLUDED.run_after),
           priority  = LEAST(q.priority,  EXCLUDED.priority),
           dirty     = q.dirty OR COALESCE(q.locked_until > now(), false);
$$;

CREATE OR REPLACE FUNCTION cp.claim_work(p_queue text, p_worker text,
                                         p_limit int DEFAULT 10, p_lease interval DEFAULT interval '60 seconds')
RETURNS TABLE (work_key text, work_attempts int) LANGUAGE sql AS $$
    WITH next AS (
        SELECT q.queue, q.key FROM cp.work_queue q
         WHERE q.queue = p_queue AND q.run_after <= now()
           AND (q.locked_until IS NULL OR q.locked_until < now())
         ORDER BY q.priority, q.run_after
         LIMIT p_limit
         FOR UPDATE SKIP LOCKED
    )
    UPDATE cp.work_queue w
       SET locked_by = p_worker, locked_until = now() + p_lease, attempts = w.attempts + 1, dirty = false
      FROM next
     WHERE w.queue = next.queue AND w.key = next.key
    RETURNING w.key, w.attempts;
$$;

CREATE OR REPLACE FUNCTION cp.finish_work(p_queue text, p_key text, p_worker text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM cp.work_queue WHERE queue = p_queue AND key = p_key AND locked_by = p_worker AND NOT dirty;
    IF NOT FOUND THEN
        UPDATE cp.work_queue
           SET locked_by = NULL, locked_until = NULL, dirty = false, attempts = 0, run_after = now()
         WHERE queue = p_queue AND key = p_key AND locked_by = p_worker;
    END IF;
END
$$;

CREATE OR REPLACE FUNCTION cp.retry_work(p_queue text, p_key text, p_worker text, p_error text)
RETURNS void LANGUAGE sql AS $$
    UPDATE cp.work_queue
       SET locked_by = NULL, locked_until = NULL, last_error = p_error,
           run_after = now() + LEAST(interval '10 minutes', interval '1 second' * power(2, attempts)) * (0.5 + random())
     WHERE queue = p_queue AND key = p_key AND locked_by = p_worker;
$$;

CREATE OR REPLACE FUNCTION cp.acquire_lease(p_name text, p_holder text, p_ttl interval)
RETURNS bigint LANGUAGE sql AS $$
    INSERT INTO cp.leases AS l (name, holder, fencing_token, expires_at)
    VALUES (p_name, p_holder, 1, now() + p_ttl)
    ON CONFLICT (name) DO UPDATE
       SET fencing_token = CASE WHEN l.holder = EXCLUDED.holder THEN l.fencing_token ELSE l.fencing_token + 1 END,
           holder = EXCLUDED.holder, expires_at = EXCLUDED.expires_at
     WHERE l.holder = EXCLUDED.holder OR l.expires_at < now()
    RETURNING fencing_token;
$$;

CREATE OR REPLACE FUNCTION cp.ingest_webhook(p_guid uuid, p_event_type text, p_action text,
                                             p_github_repo_id bigint, p_payload jsonb)
RETURNS boolean LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO cp.inbox_seen (delivery_guid) VALUES (p_guid) ON CONFLICT DO NOTHING;
    IF NOT FOUND THEN
        RETURN false;
    END IF;
    INSERT INTO cp.webhook_deliveries (delivery_guid, event_type, action, github_repo_id, payload)
    VALUES (p_guid, p_event_type, p_action, p_github_repo_id, p_payload);
    PERFORM pg_notify('cp_inbox', p_event_type);
    RETURN true;
END
$$;

-- Commit-safe event feed: a cursor (txid, seq) can never skip an event.
CREATE OR REPLACE FUNCTION cp.read_events(p_after_txid xid8, p_after_seq bigint, p_limit int)
RETURNS SETOF cp.events LANGUAGE sql STABLE AS $$
    SELECT * FROM cp.events
     WHERE (txid, seq) > (p_after_txid, p_after_seq)
       AND txid < pg_snapshot_xmin(pg_current_snapshot())
     ORDER BY txid, seq
     LIMIT p_limit
$$;

-- Pick the best credential for a workspace: active, validated, bucket not blocked,
-- most remaining budget first, then priority. Returns NULL if none is usable.
CREATE OR REPLACE FUNCTION cp.pick_credential(p_workspace_id uuid, p_need_dispatch boolean, p_resource text DEFAULT 'core')
RETURNS uuid LANGUAGE sql STABLE AS $$
    SELECT c.id
      FROM cp.github_credentials c
      JOIN cp.workspace_credentials wc ON wc.credential_id = c.id AND wc.workspace_id = p_workspace_id
      LEFT JOIN cp.github_rate_buckets b ON b.rate_bucket = c.rate_bucket AND b.resource = p_resource
     WHERE c.status = 'active'
       AND (c.expires_at IS NULL OR c.expires_at > now())
       AND (NOT p_need_dispatch OR wc.can_dispatch)
       AND COALESCE(b.breaker_state, 'closed') <> 'open'
       AND (b.blocked_until IS NULL OR b.blocked_until < now())
       AND (b.remaining IS NULL OR b.remaining > 0 OR b.resets_at < now())
     ORDER BY CASE WHEN b.resets_at < now() THEN NULL ELSE b.remaining END DESC NULLS FIRST,
              c.priority, c.last_used_at NULLS FIRST
     LIMIT 1
$$;

CREATE OR REPLACE FUNCTION cp.ensure_month_partitions(p_parent text, p_months_ahead int DEFAULT 2)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    base timestamp := date_trunc('month', now() AT TIME ZONE 'UTC');
    i int; m_start timestamp; m_end timestamp;
BEGIN
    FOR i IN 0 .. p_months_ahead LOOP
        m_start := base + make_interval(months => i);
        m_end   := base + make_interval(months => i + 1);
        EXECUTE format('CREATE TABLE IF NOT EXISTS cp.%I PARTITION OF cp.%I FOR VALUES FROM (%L) TO (%L)',
                       p_parent || '_' || to_char(m_start, 'YYYY_MM'), p_parent,
                       m_start AT TIME ZONE 'UTC', m_end AT TIME ZONE 'UTC');
    END LOOP;
END
$$;

SELECT cp.ensure_month_partitions('events', 2);
SELECT cp.ensure_month_partitions('webhook_deliveries', 2);
CREATE TABLE cp.events_default             PARTITION OF cp.events             DEFAULT;
CREATE TABLE cp.webhook_deliveries_default PARTITION OF cp.webhook_deliveries DEFAULT;

-- =====================================================================
-- 11. Database roles (map to the App Service managed identities)
--   cp_web      Next.js app: UI API, auth, webhook ingest, admin actions
--   cp_worker   reconcilers, sync, observation, token-pool bookkeeping
--   cp_readonly support / reporting
-- =====================================================================

DO $$
DECLARE r text;
BEGIN
    FOREACH r IN ARRAY ARRAY['cp_web', 'cp_worker', 'cp_readonly'] LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
            EXECUTE format('CREATE ROLE %I NOLOGIN', r);
        END IF;
    END LOOP;
END
$$;

GRANT USAGE ON SCHEMA cp, auth TO cp_web, cp_worker, cp_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA cp   TO cp_web, cp_worker, cp_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA auth TO cp_web, cp_worker;

GRANT INSERT ON cp.events TO cp_web, cp_worker;
GRANT USAGE ON SEQUENCE cp.events_seq TO cp_web, cp_worker;
GRANT INSERT, UPDATE, DELETE ON cp.work_queue TO cp_web, cp_worker;

-- Web: authentication, user intents, admin configuration, webhook inbox.
GRANT INSERT, UPDATE, DELETE ON auth.users, auth.sessions, auth.accounts, auth.verifications TO cp_web;
GRANT INSERT, UPDATE, DELETE ON cp.directory_groups, cp.user_groups TO cp_web;
GRANT INSERT ON cp.run_requests, cp.run_actions, cp.approval_requests, cp.approval_decisions TO cp_web;
GRANT UPDATE (cancel_requested, cancel_requested_by, cancel_requested_at) ON cp.run_requests TO cp_web;
GRANT UPDATE (state, decided_at) ON cp.approval_requests TO cp_web;
GRANT INSERT ON cp.workspaces TO cp_web;
GRANT UPDATE (display_name, description, visibility, public_role, status, status_reason) ON cp.workspaces TO cp_web;
GRANT INSERT, UPDATE, DELETE ON cp.workspace_grants, cp.workspace_credentials TO cp_web;
GRANT INSERT ON cp.github_credentials TO cp_web;
GRANT UPDATE (label, status, priority, secret_ref) ON cp.github_credentials TO cp_web;
-- web also calls GitHub (import validation, refs, logs, username lookup), so it reports
-- what GitHub says about a credential, exactly like the worker does
GRANT UPDATE (expires_at, last_used_at, last_error, consecutive_failures, github_account_login) ON cp.github_credentials TO cp_web;
GRANT INSERT, UPDATE ON cp.github_rate_buckets, cp.github_http_cache TO cp_web;
GRANT UPDATE (exposed, display_name, description, category, icon, ui_schema, allowed_ref_patterns,
              approval_required, approval_environments, approval_min, approval_ttl,
              concurrency_scope, concurrency_policy) ON cp.workflows TO cp_web;
-- definitions for a ref not synced yet are fetched on demand when a user opens the run form
GRANT INSERT, UPDATE ON cp.workflow_definitions TO cp_web;
GRANT SELECT, INSERT ON cp.inbox_seen TO cp_web;
GRANT INSERT ON cp.webhook_deliveries TO cp_web;

-- Worker: progress, mirror, discovery, pool bookkeeping, plumbing.
GRANT UPDATE (github_login, github_avatar_url, github_synced_at) ON auth.users TO cp_worker;
GRANT UPDATE (phase, phase_reason, phase_message, conditions, github_run_id, dispatched_with,
              dispatch_attempts, dispatch_sent_at, verify_until) ON cp.run_requests TO cp_worker;
GRANT UPDATE (phase, phase_reason, result_attempt) ON cp.run_actions TO cp_worker;
GRANT UPDATE (state, decided_at) ON cp.approval_requests TO cp_worker;
GRANT UPDATE (full_name, owner_login, repo_name, default_branch, status, status_reason, update_mode,
              github_hook_id, last_synced_at, runs_listed_until) ON cp.workspaces TO cp_worker;
GRANT UPDATE (can_dispatch, validated_at, last_error) ON cp.workspace_credentials TO cp_worker;
GRANT UPDATE (status, expires_at, last_used_at, last_error, consecutive_failures,
              github_account_login) ON cp.github_credentials TO cp_worker;
GRANT INSERT ON cp.workflows TO cp_worker;
GRANT UPDATE (path, name, gh_state) ON cp.workflows TO cp_worker;
GRANT INSERT, UPDATE ON cp.workflow_definitions, cp.workflow_runs, cp.workflow_jobs TO cp_worker;
GRANT UPDATE ON cp.webhook_deliveries TO cp_worker;
GRANT INSERT, UPDATE, DELETE ON cp.leases, cp.event_consumers, cp.github_rate_buckets,
                                cp.github_http_cache, cp.inbox_seen TO cp_worker;

COMMIT;
