import 'server-only';
import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { nextCookies } from 'better-auth/next-js';
import { and, desc, eq } from 'drizzle-orm';
import { getDb } from '../db/client';
import { accounts, sessions, users, verifications } from '../db/schema';
import { getEnv } from '../env';
import { refreshGithubIdentity, syncFromSignIn } from '../core/identity/identity';

function createAuth() {
  const env = getEnv();
  return betterAuth({
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    database: drizzleAdapter(getDb(), {
      provider: 'pg',
      schema: { users, sessions, accounts, verifications },
    }),
    user: {
      modelName: 'users',
      additionalFields: {
        role: { type: 'string', input: false, required: false, defaultValue: 'user' },
        isActive: { type: 'boolean', input: false, required: false, defaultValue: true },
      },
    },
    session: { modelName: 'sessions', expiresIn: 60 * 60 * 8, updateAge: 60 * 30 },
    account: { modelName: 'accounts' },
    verification: { modelName: 'verifications' },
    emailAndPassword: { enabled: false },
    socialProviders: {
      microsoft: {
        clientId: env.MICROSOFT_CLIENT_ID,
        clientSecret: env.MICROSOFT_CLIENT_SECRET,
        tenantId: env.MICROSOFT_TENANT_ID, // single-tenant: only our directory can sign in
        prompt: 'select_account',
      },
    },
    // Ids are UUIDv7 generated by PostgreSQL (column defaults).
    advanced: { database: { generateId: false } },
    databaseHooks: {
      session: {
        create: {
          before: async (session) => {
            const [u] = await getDb().select({ isActive: users.isActive }).from(users).where(eq(users.id, session.userId)).limit(1);
            if (u && !u.isActive) return false; // deactivated users can't sign in
            return { data: session };
          },
          after: async (session) => {
            const [account] = await getDb()
              .select({ idToken: accounts.idToken })
              .from(accounts)
              .where(and(eq(accounts.userId, session.userId), eq(accounts.providerId, 'microsoft')))
              .orderBy(desc(accounts.updatedAt))
              .limit(1);
            await syncFromSignIn(session.userId, account?.idToken);
            void refreshGithubIdentity(session.userId); // best-effort, never blocks sign-in
          },
        },
      },
    },
    plugins: [nextCookies()],
  });
}

type Auth = ReturnType<typeof createAuth>;
const globals = globalThis as typeof globalThis & { __cpAuth?: Auth };

/** Lazy so `next build` doesn't need runtime secrets. */
export function getAuth(): Auth {
  globals.__cpAuth ??= createAuth();
  return globals.__cpAuth;
}
