import 'server-only';
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { runMigrations as runBullmqMigrations } from 'bullmq';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import type pg from 'pg';
import { withOwnerRole } from './client';

/**
 * The database lifecycle (docs/design/09-jobs-and-database-lifecycle.md).
 * Nothing here is a hand-written migration:
 *   1. schema   — drizzle-kit `push` (development) or drizzle-generated migrations (production)
 *   2. guards   — drizzle/guards.sql: idempotent functions, triggers, roles, grants
 *   3. queue    — BullMQ's own runMigrations() (idempotent, advisory-locked)
 *   4. checks   — drizzle/checks/schema-checks.sql proves the invariants (rolled back)
 */

const ROOT = process.cwd();
const DRIZZLE_DIR = path.join(ROOT, 'drizzle');
const MIGRATIONS_DIR = path.join(DRIZZLE_DIR, 'migrations');
const LOCK = `select pg_advisory_lock(hashtext('cp-db-setup'))`;
const UNLOCK = `select pg_advisory_unlock(hashtext('cp-db-setup'))`;

type Log = (line: string) => void;
const defaultLog: Log = (line) => console.log(`[db] ${line}`);

async function runSqlFile(client: pg.PoolClient, file: string): Promise<void> {
  await client.query(await readFile(path.join(DRIZZLE_DIR, file), 'utf8'));
}

/** Drops everything this application owns. Development only (guarded by the CLI). */
export async function resetDatabase(log: Log = defaultLog): Promise<void> {
  await withOwnerRole(async (client) => {
    for (const schema of ['bullmq', 'cp', 'auth', 'drizzle']) {
      await client.query(`drop schema if exists ${schema} cascade`);
      log(`dropped schema ${schema}`);
    }
  });
}

/** drizzle-kit push: makes the database match server/db/schema.ts (no migration files). */
export async function pushSchema(log: Log = defaultLog): Promise<void> {
  log('drizzle-kit push --force');
  await new Promise<void>((resolve, reject) => {
    const child = spawn('npx', ['--no-install', 'drizzle-kit', 'push', '--force'], { stdio: 'inherit', env: process.env });
    child.on('error', reject);
    child.on('exit', (code) => (code === 0 ? resolve() : reject(new Error(`drizzle-kit push exited with ${code}`))));
  });
}

/** Applies drizzle-generated migrations (production). Generated by `pnpm db:generate`, never hand-written. */
export async function migrateSchema(log: Log = defaultLog): Promise<void> {
  if (!existsSync(path.join(MIGRATIONS_DIR, 'meta', '_journal.json'))) {
    throw new Error('No generated migrations found in drizzle/migrations — run `pnpm db:generate` and commit the result');
  }
  await withOwnerRole(async (client) => {
    await migrate(drizzle(client), { migrationsFolder: MIGRATIONS_DIR });
  });
  log('drizzle migrations applied');
}

/** Functions, triggers, roles and grants — idempotent, run after every push/migrate. */
export async function applyGuards(log: Log = defaultLog): Promise<void> {
  await withOwnerRole((client) => runSqlFile(client, 'guards.sql'));
  log('guards applied (functions, triggers, roles, grants)');
}

/** BullMQ's PostgreSQL schema, then grants for the web and worker roles. */
export async function migrateQueue(log: Log = defaultLog): Promise<void> {
  await withOwnerRole(async (client) => {
    await runBullmqMigrations(client);
    await runSqlFile(client, 'bullmq-grants.sql');
  });
  log('BullMQ schema migrated');
}

export interface CheckReport {
  passed: boolean;
  lines: string[];
  error?: string;
}

/** Runs drizzle/checks/schema-checks.sql (one transaction, rolled back). Use on an EMPTY database. */
export async function runSchemaChecks(log: Log = defaultLog): Promise<CheckReport> {
  const sqlText = (await readFile(path.join(DRIZZLE_DIR, 'checks', 'schema-checks.sql'), 'utf8'))
    .split('\n')
    .filter((line) => !line.startsWith('\\')) // psql meta-commands
    .join('\n');
  return withOwnerRole(async (client) => {
    const lines: string[] = [];
    const onNotice = (msg: { message?: string }) => {
      if (msg.message) {
        lines.push(msg.message);
        log(msg.message);
      }
    };
    client.on('notice', onNotice);
    try {
      await client.query(sqlText);
      return { passed: true, lines };
    } catch (err) {
      await client.query('rollback').catch(() => undefined);
      const error = (err as Error).message;
      log(error);
      return { passed: false, lines, error };
    } finally {
      client.off('notice', onNotice);
    }
  });
}

/**
 * What the worker runs on start, under an advisory lock so concurrent instances
 * (or deployment slots) set the database up exactly once.
 */
export async function setupDatabaseOnStart(mode: 'migrate' | 'guards-only', log: Log = defaultLog): Promise<void> {
  if (mode === 'migrate' && !existsSync(path.join(MIGRATIONS_DIR, 'meta', '_journal.json'))) {
    throw new Error('DB_SETUP_ON_START=migrate but drizzle/migrations is empty — run `pnpm db:generate` and commit, or use guards-only with `pnpm db:push`');
  }
  await withOwnerRole(async (client) => {
    await client.query(LOCK);
    try {
      if (mode === 'migrate') await migrate(drizzle(client), { migrationsFolder: MIGRATIONS_DIR });
      await runSqlFile(client, 'guards.sql');
      await runBullmqMigrations(client);
      await runSqlFile(client, 'bullmq-grants.sql');
    } finally {
      await client.query(UNLOCK).catch(() => undefined);
    }
  });
  log(`database ready (${mode})`);
}
